In [1]:
# pandas and numpy for data manipulation
import pandas as pd
import numpy as np

# featuretools for automated feature engineering
import featuretools as ft

In [2]:
# # Read in the datasets and replace the anomalous values
# app_train = pd.read_csv('input/application_train.csv').replace({365243: np.nan})
# app_test = pd.read_csv('input/application_test.csv').replace({365243: np.nan})
# bureau = pd.read_csv('input/bureau.csv').replace({365243: np.nan})
# bureau_balance = pd.read_csv('input/bureau_balance.csv').replace({365243: np.nan})
# cash = pd.read_csv('input/POS_CASH_balance.csv').replace({365243: np.nan})
# credit = pd.read_csv('input/credit_card_balance.csv').replace({365243: np.nan})
# previous = pd.read_csv('input/previous_application.csv').replace({365243: np.nan})
# installments = pd.read_csv('input/installments_payments.csv').replace({365243: np.nan})

In [3]:
# app_test['TARGET'] = np.nan

# # Join together training and testing
# app = pd.concat([app_train, app_test], ignore_index = True)
# app = app.sort_index()

In [4]:
# for index in ['SK_ID_CURR', 'SK_ID_PREV', 'SK_ID_BUREAU']:
#     for dataset in [app, bureau, bureau_balance, cash, credit, previous, installments]:
#         if index in list(dataset.columns):
#             dataset[index] = dataset[index].fillna(0).astype(np.int64)

In [5]:
# app.to_csv('./input/application_full.csv', index=False)
# app_train.to_csv('input/application_train.csv', index=False)
# app_test.to_csv('input/application_test.csv', index=False)
# bureau.to_csv('input/bureau.csv', index=False)
# bureau_balance.to_csv('input/bureau_balance.csv', index=False)
# cash.to_csv('input/POS_CASH_balance.csv', index=False)
# credit.to_csv('input/credit_card_balance.csv', index=False)
# previous.to_csv('input/previous_application.csv', index=False)
# installments.to_csv('input/installments_payments.csv', index=False)

In [6]:
tables = ['input/application_full.csv', 'input/bureau.csv','input/bureau_balance.csv','input/POS_CASH_balance.csv',
          'input/credit_card_balance.csv','input/previous_application.csv','input/installments_payments.csv',]

In [7]:
from gen_features import MultiDataFramesFeatureGenerator
generator = MultiDataFramesFeatureGenerator()

In [8]:
generator.load_dataframes(tables)

Loading tables...

100%|██████████| 7/7 [00:22<00:00,  3.14s/it]

Infering Dtypes...

 29%|██▊       | 2/7 [00:13<00:31,  6.25s/it]	Warning: Data size prior to feature transformation consumes 10.7% of available memory. Consider increasing memory or subsampling the data to avoid instability.
 43%|████▎     | 3/7 [00:24<00:33,  8.41s/it]	Warning: Data size prior to feature transformation consumes 6.6% of available memory. Consider increasing memory or subsampling the data to avoid instability.
 57%|█████▋    | 4/7 [00:33<00:25,  8.63s/it]	Warning: Data size prior to feature transformation consumes 5.3% of available memory. Consider increasing memory or subsampling the data to avoid instability.
 71%|███████▏  | 5/7 [00:41<00:16,  8.44s/it]	Warning: Data size prior to feature transformation consumes 10.7% of available memory. Consider increasing memory or subsampling the data to avoid instability.
100%|██████████| 7/7 [01:02<00:00,  8.93s/it]

In [9]:
generator.dataframes

[        SK_ID_CURR  TARGET  NAME_CONTRACT_TYPE CODE_GENDER  FLAG_OWN_CAR  \
 0           100002       1                True           M         False
 1           100003       0                True           F         False
 2           100004       0                True           M          True
 3           100006       0                True           F         False
 4           100007       0                True           M         False
 ...            ...     ...                 ...         ...           ...
 356250      456221    <NA>                True           F         False
 356251      456222    <NA>                True           F         False
 356252      456223    <NA>                True           F          True
 356253      456224    <NA>                True           M         False
 356254      456250    <NA>                True           F          True

         FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  \
 0                  True             0          202500.0    406597.5
 1                 False             0          270000.0   1293502.5
 2                  True             0           67500.0    135000.0
 3                  True             0          135000.0    312682.5
 4                  True             0          121500.0    513000.0
 ...                 ...           ...               ...         ...
 356250             True             0          121500.0    412560.0
 356251            False             2          157500.0    622413.0
 356252             True             1          202500.0    315000.0
 356253            False             0          225000.0    450000.0
 356254            False             0          135000.0    312768.0

         AMT_ANNUITY  ...  FLAG_DOCUMENT_18 FLAG_DOCUMENT_19 FLAG_DOCUMENT_20  \
 0           24700.5  ...             False            False            False
 1           35698.5  ...             False            False            False
 2            6750.0  ...             False            False            False
 3           29686.5  ...             False            False            False
 4           21865.5  ...             False            False            False
 ...             ...  ...               ...              ...              ...
 356250      17473.5  ...             False            False            False
 356251      31909.5  ...             False            False            False
 356252      33205.5  ...             False            False            False
 356253      25128.0  ...             False            False            False
 356254      24709.5  ...             False            False            False

        FLAG_DOCUMENT_21 AMT_REQ_CREDIT_BUREAU_HOUR AMT_REQ_CREDIT_BUREAU_DAY  \
 0                 False                          0                         0
 1                 False                          0                         0
 2                 False                          0                         0
 3                 False                       <NA>                      <NA>
 4                 False                          0                         0
 ...                 ...                        ...                       ...
 356250            False                          0                         0
 356251            False                       <NA>                      <NA>
 356252            False                          0                         0
 356253            False                          0                         0
 356254            False                          0                         0

         AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
 0                                0                          0
 1                                0                          0
 2                                0                          0
 3                             <NA>                       <NA>
 4                                0                          0
 ...                            ...                        ...
 356250                           0                          0
 356251                        <NA>                       <NA>
 356252                           0                          0
 356253                           0                          0
 356254                           0                          0

         AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR
 0                               0                           1
 1                               0                           0
 2                               0                           0
 3                            <NA>                        <NA>
 4                               0                           0
 ...                           ...                         ...
 356250                          0                           1
 356251                       <NA>                        <NA>
 356252                          3                           1
 356253                          0                           2
 356254                          1                           4

 [356255 rows x 122 columns],
          SK_ID_CURR  SK_ID_BUREAU CREDIT_ACTIVE CREDIT_CURRENCY  DAYS_CREDIT  \
 0            215354       5714462        Closed      currency 1         -497
 1            215354       5714463        Active      currency 1         -208
 2            215354       5714464        Active      currency 1         -203
 3            215354       5714465        Active      currency 1         -203
 4            215354       5714466        Active      currency 1         -629
 ...             ...           ...           ...             ...          ...
 1716423      259355       5057750        Active      currency 1          -44
 1716424      100044       5057754        Closed      currency 1        -2648
 1716425      100044       5057762        Closed      currency 1        -1809
 1716426      246829       5057770        Closed      currency 1        -1878
 1716427      246829       5057778        Closed      currency 1         -463

          CREDIT_DAY_OVERDUE  DAYS_CREDIT_ENDDATE  DAYS_ENDDATE_FACT  \
 0                         0                 -153               -153
 1                         0                 1075               <NA>
 2                         0                  528               <NA>
 3                         0                 <NA>               <NA>
 4                         0                 1197               <NA>
 ...                     ...                  ...                ...
 1716423                   0                  -30               <NA>
 1716424                   0                -2433              -2493
 1716425                   0                -1628               -970
 1716426                   0                -1513              -1513
 1716427                   0                 <NA>               -387

          AMT_CREDIT_MAX_OVERDUE  CNT_CREDIT_PROLONG  AMT_CREDIT_SUM  \
 0                           NaN                   0        91323.00
 1                           NaN                   0       225000.00
 2                           NaN                   0       464323.50
 3                           NaN                   0        90000.00
 4                       77674.5                   0      2700000.00
 ...                         ...                 ...             ...
 1716423                     0.0                   0        11250.00
 1716424                  5476.5                   0        38130.84
 1716425                     NaN                   0        15570.00
 1716426                     NaN                   0        36000.00
 1716427                     NaN                   0        22500.00

          AMT_CREDIT_SUM_DEBT  AMT_CREDIT_SUM_LIMIT  AMT_CREDIT_SUM_OVERDUE  \
 0                        0.0                   NaN                     0.0
 1                   171342.0                   NaN                     0.0
 2                        NaN                   NaN                     0.0
 3                        NaN                   NaN                     0.0
 4                        NaN                   NaN                     0.0
 ...                      ...                   ...                     ...
 1716423              11250.0                   0.0                     0.0
 1716424                  0.0                   0.0                     0.0
 1716425                  NaN                   NaN                     0.0
 1716426                  0.0                   0.0                     0.0
 1716427                  0.0                   NaN                     0.0

              CREDIT_TYPE  DAYS_CREDIT_UPDATE  AMT_ANNUITY
 0        Consumer credit                -131          NaN
 1            Credit card                 -20          NaN
 2        Consumer credit                 -16          NaN
 3            Credit card                 -16          NaN
 4        Consumer credit                 -21          NaN
 ...                  ...                 ...          ...
 1716423        Microloan                 -19          NaN
 1716424  Consumer credit               -2493          NaN
 1716425  Consumer credit                -967          NaN
 1716426  Consumer credit               -1508          NaN
 1716427        Microloan                -387          NaN

 [1716428 rows x 17 columns],
           SK_ID_BUREAU  MONTHS_BALANCE STATUS
 0              5715448               0      C
 1              5715448              -1      C
 2              5715448              -2      C
 3              5715448              -3      C
 4              5715448              -4      C
 ...                ...             ...    ...
 27299920       5041336             -47      X
 27299921       5041336             -48      X
 27299922       5041336             -49      X
 27299923       5041336             -50      X
 27299924       5041336             -51      X

 [27299925 rows x 3 columns],
           SK_ID_PREV  SK_ID_CURR  MONTHS_BALANCE  CNT_INSTALMENT  \
 0            1803195      182943             -31              48
 1            1715348      367990             -33              36
 2            1784872      397406             -32              12
 3            1903291      269225             -35              48
 4            2341044      334279             -35              36
 ...              ...         ...             ...             ...
 10001353     2448283      226558             -20               6
 10001354     1717234      141565             -19              12
 10001355     1283126      315695             -21              10
 10001356     1082516      450255             -22              12
 10001357     1259607      174278             -52              16

           CNT_INSTALMENT_FUTURE NAME_CONTRACT_STATUS  SK_DPD  SK_DPD_DEF
 0                            45               Active       0           0
 1                            35               Active       0           0
 2                             9               Active       0           0
 3                            42               Active       0           0
 4                            35               Active       0           0
 ...                         ...                  ...     ...         ...
 10001353                      0               Active     843           0
 10001354                      0               Active     602           0
 10001355                      0               Active     609           0
 10001356                      0               Active     614           0
 10001357                      0            Completed       0           0

 [10001358 rows x 8 columns],
          SK_ID_PREV  SK_ID_CURR  MONTHS_BALANCE  AMT_BALANCE  \
 0           2562384      378907              -6       56.970
 1           2582071      363914              -1    63975.555
 2           1740877      371185              -7    31815.225
 3           1389973      337855              -4   236572.110
 4           1891521      126868              -1   453919.455
 ...             ...         ...             ...          ...
 3840307     1036507      328243              -9        0.000
 3840308     1714892      347207              -9        0.000
 3840309     1302323      215757              -9   275784.975
 3840310     1624872      430337             -10        0.000
 3840311     2411345      236760             -10        0.000

          AMT_CREDIT_LIMIT_ACTUAL  AMT_DRAWINGS_ATM_CURRENT  \
 0                         135000                       0.0
 1                          45000                    2250.0
 2                         450000                       0.0
 3                         225000                    2250.0
 4                         450000                       0.0
 ...                          ...                       ...
 3840307                    45000                       NaN
 3840308                    45000                       0.0
 3840309                   585000                  270000.0
 3840310                   450000                       NaN
 3840311                   157500                       0.0

          AMT_DRAWINGS_CURRENT  AMT_DRAWINGS_OTHER_CURRENT  \
 0                       877.5                         0.0
 1                      2250.0                         0.0
 2                         0.0                         0.0
 3                      2250.0                         0.0
 4                     11547.0                         0.0
 ...                       ...                         ...
 3840307                   0.0                         NaN
 3840308                   0.0                         0.0
 3840309              270000.0                         0.0
 3840310                   0.0                         NaN
 3840311                   0.0                         0.0

          AMT_DRAWINGS_POS_CURRENT  AMT_INST_MIN_REGULARITY  ...  \
 0                           877.5                 1700.325  ...
 1                             0.0                 2250.000  ...
 2                             0.0                 2250.000  ...
 3                             0.0                11795.760  ...
 4                         11547.0                22924.890  ...
 ...                           ...                      ...  ...
 3840307                       NaN                    0.000  ...
 3840308                       0.0                    0.000  ...
 3840309                       0.0                 2250.000  ...
 3840310                       NaN                    0.000  ...
 3840311                       0.0                    0.000  ...

          AMT_RECIVABLE  AMT_TOTAL_RECEIVABLE  CNT_DRAWINGS_ATM_CURRENT  \
 0                0.000                 0.000                         0
 1            64875.555             64875.555                         1
 2            31460.085             31460.085                         0
 3           233048.970            233048.970                         1
 4           453919.455            453919.455                         0
 ...                ...                   ...                       ...
 3840307          0.000                 0.000                      <NA>
 3840308          0.000                 0.000                         0
 3840309     273093.975            273093.975                         2
 3840310          0.000                 0.000                      <NA>
 3840311          0.000                 0.000                         0

          CNT_DRAWINGS_CURRENT  CNT_DRAWINGS_OTHER_CURRENT  \
 0                           1                           0
 1                           1                           0
 2                           0                           0
 3                           1                           0
 4                           1                           0
 ...                       ...                         ...
 3840307                     0                        <NA>
 3840308                     0                           0
 3840309                     2                           0
 3840310                     0                        <NA>
 3840311                     0                           0

          CNT_DRAWINGS_POS_CURRENT  CNT_INSTALMENT_MATURE_CUM  \
 0                               1                         35
 1                               0                         69
 2                               0                         30
 3                               0                         10
 4                               1                        101
 ...                           ...                        ...
 3840307                      <NA>                          0
 3840308                         0                         23
 3840309                         0                         18
 3840310                      <NA>                          0
 3840311                         0                         21

          NAME_CONTRACT_STATUS  SK_DPD  SK_DPD_DEF
 0                      Active       0           0
 1                      Active       0           0
 2                      Active       0           0
 3                      Active       0           0
 4                      Active       0           0
 ...                       ...     ...         ...
 3840307                Active       0           0
 3840308                Active       0           0
 3840309                Active       0           0
 3840310                Active       0           0
 3840311             Completed       0           0

 [3840312 rows x 23 columns],
          SK_ID_PREV  SK_ID_CURR NAME_CONTRACT_TYPE  AMT_ANNUITY  \
 0           2030495      271877     Consumer loans     1730.430
 1           2802425      108129         Cash loans    25188.615
 2           2523466      122040         Cash loans    15060.735
 3           2819243      176158         Cash loans    47041.335
 4           1784265      202054         Cash loans    31924.395
 ...             ...         ...                ...          ...
 1670209     2300464      352015     Consumer loans    14704.290
 1670210     2357031      334635     Consumer loans     6622.020
 1670211     2659632      249544     Consumer loans    11520.855
 1670212     2785582      400317         Cash loans    18821.520
 1670213     2418762      261212         Cash loans    16431.300

          AMT_APPLICATION  AMT_CREDIT  AMT_DOWN_PAYMENT  AMT_GOODS_PRICE  \
 0                17145.0     17145.0               0.0          17145.0
 1               607500.0    679671.0               NaN         607500.0
 2               112500.0    136444.5               NaN         112500.0
 3               450000.0    470790.0               NaN         450000.0
 4               337500.0    404055.0               NaN         337500.0
 ...                  ...         ...               ...              ...
 1670209         267295.5    311400.0               0.0         267295.5
 1670210          87750.0     64291.5           29250.0          87750.0
 1670211         105237.0    102523.5           10525.5         105237.0
 1670212         180000.0    191880.0               NaN         180000.0
 1670213         360000.0    360000.0               NaN         360000.0

         WEEKDAY_APPR_PROCESS_START  HOUR_APPR_PROCESS_START  ...  \
 0                         SATURDAY                       15  ...
 1                         THURSDAY                       11  ...
 2                          TUESDAY                       11  ...
 3                           MONDAY                        7  ...
 4                         THURSDAY                        9  ...
 ...                            ...                      ...  ...
 1670209                  WEDNESDAY                       12  ...
 1670210                    TUESDAY                       15  ...
 1670211                     MONDAY                       12  ...

In [10]:
generator.rename_dataframe(0, 'app')
generator.rename_dataframe(3, 'cash')
generator.rename_dataframe(4, 'credit')
generator.rename_dataframe(5, 'previous')
generator.rename_dataframe(6, 'installments')

In [11]:
generator.set_index(0, 'SK_ID_CURR')
generator.set_index(1, 'SK_ID_BUREAU')
generator.set_index(5, 'SK_ID_PREV')

In [12]:
relationships = [
    ('app', 'SK_ID_CURR', 'bureau', 'SK_ID_CURR',),
	('bureau', 'SK_ID_BUREAU', 'bureau_balance', 'SK_ID_BUREAU',),
	('app', 'SK_ID_CURR', 'previous', 'SK_ID_CURR',),
	('previous', 'SK_ID_PREV', 'cash', 'SK_ID_PREV',),
	('previous', 'SK_ID_PREV', 'installments', 'SK_ID_PREV',),
	('previous', 'SK_ID_PREV', 'credit', 'SK_ID_PREV',),
]
[generator.add_relationship(r) for r in relationships]

[None, None, None, None, None, None]

In [13]:
generator.relationships

[('app', 'SK_ID_CURR', 'bureau', 'SK_ID_CURR'),
 ('bureau', 'SK_ID_BUREAU', 'bureau_balance', 'SK_ID_BUREAU'),
 ('app', 'SK_ID_CURR', 'previous', 'SK_ID_CURR'),
 ('previous', 'SK_ID_PREV', 'cash', 'SK_ID_PREV'),
 ('previous', 'SK_ID_PREV', 'installments', 'SK_ID_PREV'),
 ('previous', 'SK_ID_PREV', 'credit', 'SK_ID_PREV')]

In [14]:
generator.compile()

creating index for column bureau_balance
creating index for column cash
creating index for column credit
creating index for column installments

In [15]:
generator._es.dataframes[0].ww

                           Physical Type     Logical Type Semantic Tag(s)
Column
SK_ID_CURR                         int64          Integer       ['index']
TARGET                             Int64  IntegerNullable     ['numeric']
NAME_CONTRACT_TYPE                  bool          Boolean              []
CODE_GENDER                     category      Categorical    ['category']
FLAG_OWN_CAR                        bool          Boolean              []
...                                  ...              ...             ...
AMT_REQ_CREDIT_BUREAU_DAY          Int64  IntegerNullable     ['numeric']
AMT_REQ_CREDIT_BUREAU_WEEK         Int64  IntegerNullable     ['numeric']
AMT_REQ_CREDIT_BUREAU_MON          Int64  IntegerNullable     ['numeric']
AMT_REQ_CREDIT_BUREAU_QRT          Int64  IntegerNullable     ['numeric']
AMT_REQ_CREDIT_BUREAU_YEAR         Int64  IntegerNullable     ['numeric']

[122 rows x 3 columns]

In [16]:
import pandas as pd
import woodwork
from gen_features import ww_init


df = pd.DataFrame({"a": [1,2,3,4], 'b': [True, False, False,None],
                   'c': [15, 15, 12, 15,],
                   't': ['2023-01-01', '2019-01-23', '2021-12-12', '2022-12-11']})
# df.t = pd.to_datetime(df.t, format='%Y-%m-%d').dt.strftime("%d-%m-%Y")

# from autogluon.features.generators import AutoMLPipelineFeatureGenerator, DropUniqueFeatureGenerator
# ag_dtype_infer =AutoMLPipelineFeatureGenerator(post_generators=[DropUniqueFeatureGenerator(1.0)], post_drop_duplicates=False)
# ag_dtype_infer.fit_transform(df)
# df.ww.init()
ww_init(df, 'abcdf')
df

   a      b     c          t
0  1   True  True 2023-01-01
1  2  False  True 2019-01-23
2  3  False  True 2021-12-12
3  4    NaN  True 2022-12-11

In [17]:
generator.plot('./relationships.svg')

## Run Full Deep Feature Synthesis

If we are content with the features that will be built, we can run deep feature synthesis and create the feature matrix. The following call runs the full deep feature synthesis. This might take a long time depending on your machine. Featuretools does allow for parallel processing, but each core must be able to handle the entire entityset. 

__An actual run of this code was completed using Dask which can be seen in the [Featuretools on Dask notebook](https://github.com/Featuretools/Automated-Manual-Comparison/blob/master/Loan%20Repayment/notebooks/Featuretools%20on%20Dask.ipynb).__ The Dask code takes under 2 hours to run and is a great example of how we can use parallel processing to use our resouces in the most efficient manner.

In [18]:
import sys
print('Total size of entityset: {:.5f} gb.'.format(sys.getsizeof(generator._es) / 1e9))

Total size of entityset: 4.28069 gb.

In [19]:
import psutil

print('Total number of cpus detected: {}.'.format(psutil.cpu_count()))
print('Total size of system memory: {:.5f} gb.'.format(psutil.virtual_memory().total / 1e9))

Total number of cpus detected: 12.
Total size of system memory: 24.92599 gb.

In [20]:
agg_primitives =  ["mean","percent_true", ]
trans_primitives = ['percentile', 'and']

In [21]:
# import time
# time.sleep(1e5)

In [22]:
label = 'TARGET'

In [23]:
result_df = generator.generate_features('app', max_depth=2, verbose=True, chunk_size=50,
                                        # agg_primitives=agg_primitives, trans_primitives=trans_primitives,
                                        ignore_columns={'app': [label]})

/home/minhduck/Documents/projects/vnstock/venv/lib/python3.10/site-packages/featuretools/synthesis/dfs.py:321: UnusedPrimitiveWarning: Some specified primitives were not used during DFS:
  trans_primitives: ['day', 'month', 'weekday']
This may be caused by a using a value of max_depth that is too small, not setting interesting values, or it may indicate no compatible columns for the primitive were found in the data. If the DFS call contained multiple instances of a primitive in the list above, none of them were used.
  warnings.warn(warning_msg, UnusedPrimitiveWarning)

Built 1727 features
Elapsed: 2:25:33 | Progress: 100%|██████████

In [24]:
result_df.shape

(356255, 1727)

In [25]:
result_df.columns

Index(['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY',
       'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY',
       'AMT_GOODS_PRICE', 'NAME_TYPE_SUITE',
       ...
       'PERCENTILE(SUM(previous.DAYS_FIRST_DUE))',
       'PERCENTILE(SUM(previous.DAYS_LAST_DUE))',
       'PERCENTILE(SUM(previous.DAYS_LAST_DUE_1ST_VERSION))',
       'PERCENTILE(SUM(previous.DAYS_TERMINATION))',
       'PERCENTILE(SUM(previous.HOUR_APPR_PROCESS_START))',
       'PERCENTILE(SUM(previous.NFLAG_INSURED_ON_APPROVAL))',
       'PERCENTILE(SUM(previous.RATE_DOWN_PAYMENT))',
       'PERCENTILE(SUM(previous.RATE_INTEREST_PRIMARY))',
       'PERCENTILE(SUM(previous.RATE_INTEREST_PRIVILEGED))',
       'PERCENTILE(SUM(previous.SELLERPLACE_AREA))'],
      dtype='object', length=1727)

In [26]:
result_df[label] = generator.dataframes[0][label]

In [27]:
df_train = result_df[~result_df[label].isna()]
df_test = result_df[result_df[label].isna()]

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(df_train.drop(columns=[label]), df_train[label], train_size=0.9, random_state=42)

df_train = pd.concat([X_train, y_train], axis=1)
df_val = pd.concat([X_val, y_val], axis=1)

In [29]:
df_train.to_csv('train.csv')
df_val.to_csv('val.csv')
df_test.to_csv('test.csv')

# Feature Selection

In [1]:
from autogluon.tabular import TabularPredictor
from datetime import datetime
import pandas as pd
import featurewiz



df_train= pd.read_csv('train.csv')
df_val= pd.read_csv('val.csv')
df_test= pd.read_csv('test.csv')
label = 'TARGET'
id_cols = ['SK_ID_CURR','SK_ID_BUREAU','SK_ID_PREV',]

2024-02-01 21:15:00.953542: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-02-01 21:15:01.112178: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-01 21:15:01.112227: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-01 21:15:01.140651: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-02-01 21:15:01.191307: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-01 21:15:01.962637: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

Imported lazytransform v1.14.

Imported featurewiz 0.5.4. Use the following syntax:
    >>> wiz = FeatureWiz(feature_engg = '', nrows=None, transform_target=True, scalers="std",
        		category_encoders="auto", add_missing=False, verbose=0. imbalanced=False,
        		ae_options={})
    >>> X_train_selected, y_train = wiz.fit_transform(X_train, y_train)
    >>> X_test_selected = wiz.transform(X_test)
    >>> selected_features = wiz.features

In [2]:
X_train, y_train = df_train.drop(columns=[label, *id_cols], errors='ignore'), df_train[label]
X_val, y_val = df_val.drop(columns=[label, *id_cols], errors='ignore'), df_val[label]
X_test, y_test = df_test.drop(columns=[label, *id_cols], errors='ignore'), df_test[label]

df_wiz = pd.concat([df_train, df_val], ignore_index=True)
X_wiz, y_wiz = df_wiz.drop(columns=[label, *id_cols], errors='ignore'), df_wiz[label]

In [3]:
wiz = featurewiz.FeatureWiz(feature_engg = '', nrows=None, transform_target=True, scalers="std",
        		category_encoders="auto", add_missing=False, verbose=0, imbalanced=False, 
                ae_options={})

X_wiz_transform, y_wiz = wiz.fit_transform(X_wiz, y_wiz)

featurewiz is given 0.9 as correlation limit...
    Skipping feature engineering since no feature_engg input...
    final list of category encoders given: ['onehot', 'label']
    final list of scalers given: [std]
Loaded input data. Shape = (307511, 1727)
    Warning: Too many features will be generated since categorical vars > 10. This may take time...
#### Starting featurewiz transform for train data ####
    Single_Label Binary_Classification problem
Shape of dataset: (307511, 1727). Now we classify variables into different types...
Time taken to define data pipeline = 601 second(s)
No model input given...
Lazy Transformer Pipeline created...
    transformed target from object type to numeric
    Time taken to fit dataset = 660 second(s)
    Time taken to transform dataset = 695 second(s)
    Shape of transformed dataset: (307511, 2269)
    Single_Label Binary_Classification problem
Starting SULOV with 2172 features...
    there are no null values in dataset...
    there are no null values in target column...
Completed SULOV. 1057 features selected
Performing recursive XGBoost feature selection from 1057 features...
    time taken to run entire featurewiz = 6313 second(s)
Recursive XGBoost selected 354 features...

In [4]:
X_train.shape, X_val.shape, X_wiz.shape

((276759, 1727), (30752, 1727), (307511, 1727))

In [5]:
X_train_transform = wiz.transform(X_train)
X_val_transform = wiz.transform(X_val)
X_test_transform = wiz.transform(X_test)

#### Starting featurewiz transform for test data ####
Loaded input data. Shape = (276759, 1727)
#### Starting lazytransform for test data ####
    Time taken to transform dataset = 25 second(s)
    Shape of transformed dataset: (276759, 2269)
Returning dataframe with 354 features
#### Starting featurewiz transform for test data ####
Loaded input data. Shape = (30752, 1727)
#### Starting lazytransform for test data ####
    Time taken to transform dataset = 2 second(s)
    Shape of transformed dataset: (30752, 2269)
Returning dataframe with 354 features
#### Starting featurewiz transform for test data ####
Loaded input data. Shape = (48744, 1727)
#### Starting lazytransform for test data ####
    Time taken to transform dataset = 3 second(s)
    Shape of transformed dataset: (48744, 2269)
Returning dataframe with 354 features

In [6]:
for col in id_cols:
	if col not in df_train.columns: continue
	X_train_transform[col] = df_train[col]
	X_val_transform[col] = df_val[col]
	X_test_transform[col] = df_test[col]


train_df = pd.concat([X_train_transform, y_train], axis=1)
val_df = pd.concat([X_val_transform, y_val], axis=1)
test_df = pd.concat([X_test_transform, y_test], axis=1)

In [12]:
train_df.to_csv('train_pruned.csv')
val_df.to_csv('val_pruned.csv')
test_df.to_csv('test_pruned.csv')

# Training

In [6]:
from autogluon.tabular import TabularPredictor
from datetime import datetime
import pandas as pd


train_df = pd.read_csv('train_pruned.csv')
val_df = pd.read_csv('val_pruned.csv')
test_df = pd.read_csv('test_pruned.csv')
label = "TARGET"

In [2]:
from autogluon.tabular.configs.hyperparameter_configs import get_hyperparameter_config
get_hyperparameter_config('multimodal')

{'NN_TORCH': {},
 'GBM': [{},
  {'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}},
  'GBMLarge'],
 'CAT': {},
 'XGB': {},
 'AG_AUTOMM': {},
 'VW': {}}

In [3]:

kwargs = {
    'time_limit': 7200,
    'presets': 'medium_quality',
    'hyperparameters': {
        'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}},
                 {},
                #  {'boosting': 'dart', 'ag_args': {'name_suffix': 'dart'}},
                 'GBMLarge'
                ],
         'CAT': {},
         'XGB': {},
        'AG_AUTOMM': {}, 'VW': {}
    },
	"ag_args_fit":{"ag.max_memory_usage_ratio": 6.0},
	"ag_args_ensemble":{"fold_fitting_strategy":"sequential_local"},
}
predictor = TabularPredictor(label, eval_metric='roc_auc')
predictor.fit(
        train_df, tuning_data=val_df,
        # pd.concat([train_df, val_df], ignore_index=True), 
              **kwargs)

No path specified. Models will be saved in: "AutogluonModels/ag-20240226_134632"
Presets specified: ['medium_quality']
Beginning AutoGluon training ... Time limit = 7200s
AutoGluon will save models to "AutogluonModels/ag-20240226_134632"
=================== System Info ===================
AutoGluon Version:  1.0.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #21~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb  9 13:32:52 UTC 2
CPU Count:          12
Memory Avail:       14.42 GB / 23.21 GB (62.1%)
Disk Space Avail:   368.76 GB / 465.76 GB (79.2%)
===================================================
Train Data Rows:    276759
Train Data Columns: 356
Tuning Data Rows:    30752
Tuning Data Columns: 356
Label Column:       TARGET
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [0, 1]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression'])
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    14433.92 MB
	Train Data (Original)  Memory Usage: 835.22 MB (5.8% of available memory)
	Warning: Data size prior to feature transformation consumes 5.8% of available memory. Consider increasing memory or subsampling the data to avoid instability.
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 39 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 3): ['MAX(previous.MIN(cash.SK_ID_CURR))', 'SUM(cash.previous.AMT_APPLICATION)', 'SUM(previous.MAX(cash.SK_ID_CURR))']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('float', []) : 3 | ['MAX(previous.MIN(cash.SK_ID_CURR))', 'SUM(cash.previous.AMT_APPLICATION)', 'SUM(previous.MAX(cash.SK_ID_CURR))']
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 308 | ['EXT_SOURCE_3', 'PERCENTILE(EXT_SOURCE_2)', 'EXT_SOURCE_1', 'PERCENTILE(DAYS_EMPLOYED)', 'MAX(previous.MIN(installments.AMT_PAYMENT))', ...]
		('int', [])   :  45 | ['Unnamed: 0', 'NAME_EDUCATION_TYPE_Highereducation', 'CODE_GENDER_M', 'MODEpreviousNAME_CONTRACT_STATUS_Refused', 'DAYS_BIRTH', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])     : 308 | ['EXT_SOURCE_3', 'PERCENTILE(EXT_SOURCE_2)', 'EXT_SOURCE_1', 'PERCENTILE(DAYS_EMPLOYED)', 'MAX(previous.MIN(installments.AMT_PAYMENT))', ...]
		('int', [])       :   6 | ['Unnamed: 0', 'DAYS_BIRTH', 'DAYS_ID_PUBLISH', 'ORGANIZATION_TYPE_encoded', 'HOUR_APPR_PROCESS_START', ...]
		('int', ['bool']) :  39 | ['NAME_EDUCATION_TYPE_Highereducation', 'CODE_GENDER_M', 'MODEpreviousNAME_CONTRACT_STATUS_Refused', 'MODEcashpreviousNAME_YIELD_GROUP_high', 'NAME_EDUCATION_TYPE_Secondarysecondaryspecial', ...]
	5.7s = Fit runtime
	353 features in original data used to generate 353 features in processed data.
	Train Data (Processed) Memory Usage: 748.12 MB (5.2% of available memory)
Data preprocessing and feature engineering runtime = 6.41s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': [{'booster': 'gbtree', 'ag_args': {'name_suffix': 'tree'}}, {'booster': 'gbtree', 'ag_args': {'name_suffix': 'tree_1'}, 'max_depth': 8, 'gamma': 0.01, 'colsample_bytree': 0.8, 'subsample': 0.8, 'lambda': 2}, {'booster': 'gbtree', 'ag_args': {'name_suffix': 'tree_2'}, 'max_depth': 10, 'gamma': 0.01, 'colsample_bytree': 0.6, 'subsample': 0.6, 'lambda': 4}, {'booster': 'gbtree', 'ag_args': {'name_suffix': 'tree_3'}, 'max_depth': 8, 'gamma': 0.01, 'colsample_bytree': 0.95, 'subsample': 0.95, 'lambda': 1}, {'booster': 'gbtree', 'ag_args': {'name_suffix': 'tree_4'}, 'max_depth': 10, 'gamma': 0.01, 'colsample_bytree': 0.9, 'subsample': 0.9, 'lambda': 2}],
	'AG_AUTOMM': {},
	'VW': {},
}
Fitting 11 L1 models ...
Fitting model: LightGBMXT ... Training model for up to 7193.59s of the 7193.59s of remaining time.

[1000]	valid_set's binary_logloss: 0.241386

	0.7806	 = Validation score   (roc_auc)
	291.37s	 = Training   runtime
	0.87s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 6901.08s of the 6901.08s of remaining time.
	0.7811	 = Validation score   (roc_auc)
	228.35s	 = Training   runtime
	0.2s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 6672.5s of the 6672.5s of remaining time.
	0.7846	 = Validation score   (roc_auc)
	200.86s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: XGBoosttree ... Training model for up to 6471.58s of the 6471.58s of remaining time.
	0.779	 = Validation score   (roc_auc)
	86.76s	 = Training   runtime
	0.27s	 = Validation runtime
Fitting model: XGBoosttree_1 ... Training model for up to 6384.51s of the 6384.51s of remaining time.
	0.7755	 = Validation score   (roc_auc)
	74.6s	 = Training   runtime
	0.34s	 = Validation runtime
Fitting model: XGBoosttree_2 ... Training model for up to 6309.55s of the 6309.55s of remaining time.
	0.7731	 = Validation score   (roc_auc)
	69.76s	 = Training   runtime
	0.35s	 = Validation runtime
Fitting model: XGBoosttree_3 ... Training model for up to 6239.43s of the 6239.43s of remaining time.
	0.7759	 = Validation score   (roc_auc)
	96.91s	 = Training   runtime
	0.31s	 = Validation runtime
Fitting model: XGBoosttree_4 ... Training model for up to 6142.17s of the 6142.17s of remaining time.
	0.7753	 = Validation score   (roc_auc)
	66.89s	 = Training   runtime
	0.27s	 = Validation runtime
Fitting model: VowpalWabbit ... Training model for up to 6074.98s of the 6074.98s of remaining time.
	Warning: Exception caused VowpalWabbit to fail during training... Skipping this model.
		Currently, we only support vowpalwabbit version >=9.0 and <9.9. Found vowpalwabbit version: 9.9.0
Detailed Traceback:
Traceback (most recent call last):
  File "/media/minhduck/SSD1/Documents/projects/pyenvs/automl/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1817, in _train_and_save
    model = self._train_single(X, y, model, X_val, y_val, total_resources=total_resources, **model_fit_kwargs)
  File "/media/minhduck/SSD1/Documents/projects/pyenvs/automl/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1763, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, total_resources=total_resources, **model_fit_kwargs)
  File "/media/minhduck/SSD1/Documents/projects/pyenvs/automl/lib/python3.10/site-packages/autogluon/core/models/abstract/abstract_model.py", line 854, in fit
    out = self._fit(**kwargs)
  File "/media/minhduck/SSD1/Documents/projects/pyenvs/automl/lib/python3.10/site-packages/autogluon/tabular/models/vowpalwabbit/vowpalwabbit_model.py", line 68, in _fit
    try_import_vowpalwabbit()
  File "/media/minhduck/SSD1/Documents/projects/pyenvs/automl/lib/python3.10/site-packages/autogluon/common/utils/try_import.py", line 177, in try_import_vowpalwabbit
    assert vowpalwabbit_version >= parse_version("9.0.0") and vowpalwabbit_version < parse_version(
AssertionError: Currently, we only support vowpalwabbit version >=9.0 and <9.9. Found vowpalwabbit version: 9.9.0
Fitting model: LightGBMLarge ... Training model for up to 6073.95s of the 6073.95s of remaining time.
	0.7814	 = Validation score   (roc_auc)
	65.19s	 = Training   runtime
	0.15s	 = Validation runtime
Fitting model: MultiModalPredictor ... Training model for up to 6008.56s of the 6008.56s of remaining time.
Global seed set to 0
Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA GeForce RTX 3050 Laptop GPU') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name              | Type             | Params
-------------------------------------------------------
0 | model             | FT_Transformer   | 953 K
1 | validation_metric | BinaryAUROC      | 0
2 | loss_func         | CrossEntropyLoss | 0
-------------------------------------------------------
953 K     Trainable params
0         Non-trainable params
953 K     Total params
3.815     Total estimated model params size (MB)
Epoch 0, global step 1081: 'val_roc_auc' reached 0.72435 (best 0.72435), saving model to '/media/minhduck/SSD1/Documents/projects/AutoML-Platform/src/mlservice/app/test/relational_test/AutogluonModels/ag-20240226_134632/models/MultiModalPredictor/automm_model/epoch=0-step=1081.ckpt' as top 3
Epoch 0, global step 2162: 'val_roc_auc' reached 0.75489 (best 0.75489), saving model to '/media/minhduck/SSD1/Documents/projects/AutoML-Platform/src/mlservice/app/test/relational_test/AutogluonModels/ag-20240226_134632/models/MultiModalPredictor/automm_model/epoch=0-step=2162.ckpt' as top 3
Epoch 1, global step 3244: 'val_roc_auc' reached 0.75765 (best 0.75765), saving model to '/media/minhduck/SSD1/Documents/projects/AutoML-Platform/src/mlservice/app/test/relational_test/AutogluonModels/ag-20240226_134632/models/MultiModalPredictor/automm_model/epoch=1-step=3244.ckpt' as top 3
Epoch 1, global step 4325: 'val_roc_auc' reached 0.76152 (best 0.76152), saving model to '/media/minhduck/SSD1/Documents/projects/AutoML-Platform/src/mlservice/app/test/relational_test/AutogluonModels/ag-20240226_134632/models/MultiModalPredictor/automm_model/epoch=1-step=4325.ckpt' as top 3
Epoch 2, global step 5407: 'val_roc_auc' reached 0.76044 (best 0.76152), saving model to '/media/minhduck/SSD1/Documents/projects/AutoML-Platform/src/mlservice/app/test/relational_test/AutogluonModels/ag-20240226_134632/models/MultiModalPredictor/automm_model/epoch=2-step=5407.ckpt' as top 3
Epoch 2, global step 6488: 'val_roc_auc' reached 0.76184 (best 0.76184), saving model to '/media/minhduck/SSD1/Documents/projects/AutoML-Platform/src/mlservice/app/test/relational_test/AutogluonModels/ag-20240226_134632/models/MultiModalPredictor/automm_model/epoch=2-step=6488.ckpt' as top 3
Epoch 3, global step 7570: 'val_roc_auc' reached 0.76354 (best 0.76354), saving model to '/media/minhduck/SSD1/Documents/projects/AutoML-Platform/src/mlservice/app/test/relational_test/AutogluonModels/ag-20240226_134632/models/MultiModalPredictor/automm_model/epoch=3-step=7570.ckpt' as top 3
Epoch 3, global step 8651: 'val_roc_auc' reached 0.76272 (best 0.76354), saving model to '/media/minhduck/SSD1/Documents/projects/AutoML-Platform/src/mlservice/app/test/relational_test/AutogluonModels/ag-20240226_134632/models/MultiModalPredictor/automm_model/epoch=3-step=8651.ckpt' as top 3
Epoch 4, global step 9733: 'val_roc_auc' reached 0.76555 (best 0.76555), saving model to '/media/minhduck/SSD1/Documents/projects/AutoML-Platform/src/mlservice/app/test/relational_test/AutogluonModels/ag-20240226_134632/models/MultiModalPredictor/automm_model/epoch=4-step=9733.ckpt' as top 3
Epoch 4, global step 10814: 'val_roc_auc' reached 0.76637 (best 0.76637), saving model to '/media/minhduck/SSD1/Documents/projects/AutoML-Platform/src/mlservice/app/test/relational_test/AutogluonModels/ag-20240226_134632/models/MultiModalPredictor/automm_model/epoch=4-step=10814.ckpt' as top 3
Epoch 5, global step 11896: 'val_roc_auc' reached 0.76443 (best 0.76637), saving model to '/media/minhduck/SSD1/Documents/projects/AutoML-Platform/src/mlservice/app/test/relational_test/AutogluonModels/ag-20240226_134632/models/MultiModalPredictor/automm_model/epoch=5-step=11896.ckpt' as top 3
Epoch 5, global step 12977: 'val_roc_auc' reached 0.76548 (best 0.76637), saving model to '/media/minhduck/SSD1/Documents/projects/AutoML-Platform/src/mlservice/app/test/relational_test/AutogluonModels/ag-20240226_134632/models/MultiModalPredictor/automm_model/epoch=5-step=12977.ckpt' as top 3
Epoch 6, global step 14059: 'val_roc_auc' reached 0.76672 (best 0.76672), saving model to '/media/minhduck/SSD1/Documents/projects/AutoML-Platform/src/mlservice/app/test/relational_test/AutogluonModels/ag-20240226_134632/models/MultiModalPredictor/automm_model/epoch=6-step=14059.ckpt' as top 3
Epoch 6, global step 15140: 'val_roc_auc' reached 0.76860 (best 0.76860), saving model to '/media/minhduck/SSD1/Documents/projects/AutoML-Platform/src/mlservice/app/test/relational_test/AutogluonModels/ag-20240226_134632/models/MultiModalPredictor/automm_model/epoch=6-step=15140.ckpt' as top 3
Epoch 7, global step 16222: 'val_roc_auc' reached 0.76930 (best 0.76930), saving model to '/media/minhduck/SSD1/Documents/projects/AutoML-Platform/src/mlservice/app/test/relational_test/AutogluonModels/ag-20240226_134632/models/MultiModalPredictor/automm_model/epoch=7-step=16222.ckpt' as top 3
Epoch 7, global step 17303: 'val_roc_auc' reached 0.76909 (best 0.76930), saving model to '/media/minhduck/SSD1/Documents/projects/AutoML-Platform/src/mlservice/app/test/relational_test/AutogluonModels/ag-20240226_134632/models/MultiModalPredictor/automm_model/epoch=7-step=17303.ckpt' as top 3
Epoch 8, global step 18385: 'val_roc_auc' reached 0.76943 (best 0.76943), saving model to '/media/minhduck/SSD1/Documents/projects/AutoML-Platform/src/mlservice/app/test/relational_test/AutogluonModels/ag-20240226_134632/models/MultiModalPredictor/automm_model/epoch=8-step=18385.ckpt' as top 3
Epoch 8, global step 19466: 'val_roc_auc' was not in top 3
Time limit reached. Elapsed time is 1:40:08. Signaling Trainer to stop.
Epoch 9, global step 19471: 'val_roc_auc' was not in top 3
`Trainer.fit` stopped: `max_epochs=10` reached.
	0.7697	 = Validation score   (roc_auc)
	6114.86s	 = Training   runtime
	18.73s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 719.36s of the -125.08s of remaining time.
	Ensemble Weights: {'CatBoost': 0.447, 'XGBoosttree_4': 0.149, 'LightGBMLarge': 0.149, 'MultiModalPredictor': 0.106, 'XGBoosttree_2': 0.064, 'XGBoosttree_3': 0.064, 'LightGBM': 0.021}
	0.7872	 = Validation score   (roc_auc)
	3.04s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 7330.76s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240226_134632")

In [7]:
from autogluon.tabular import TabularPredictor
predictor = TabularPredictor.load("AutogluonModels/ag-20240226_134632")
predictor.leaderboard(val_df, extra_metrics=['accuracy', 'roc_auc', 'precision', 'recall', 'f1']).to_csv('leaderboard.csv')

<class 'inspect._empty'>
<class 'inspect._empty'>
<class 'inspect._empty'>
<class 'inspect._empty'>

Load pretrained checkpoint: /media/minhduck/SSD1/Documents/projects/AutoML-Platform/src/mlservice/app/test/relational_test/AutogluonModels/ag-20240226_134632/models/MultiModalPredictor/automm_model/model.ckpt
You are using a CUDA device ('NVIDIA GeForce RTX 3050 Laptop GPU') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision

Predicting DataLoader 0: 100%|██████████| 961/961 [00:19<00:00, 49.08it/s]

In [4]:
predictor.leaderboard(val_df, extra_metrics=['accuracy', 'roc_auc'])

Load pretrained checkpoint: /media/minhduck/SSD1/Documents/projects/AutoML-Platform/src/mlservice/app/test/relational_test/AutogluonModels/ag-20240226_134632/models/MultiModalPredictor/automm_model/model.ckpt

Predicting DataLoader 0: 100%|██████████| 961/961 [00:18<00:00, 52.36it/s]

,model,score_test,accuracy,roc_auc,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,WeightedEnsemble_L2,0.787219,0.919355,0.787219,0.787219,roc_auc,20.113111,20.052561,6845.866517,0.004305,0.003055,3.039491,2,True,11
1,CatBoost,0.784627,0.919745,0.784627,0.784627,roc_auc,0.057204,0.037113,200.862975,0.057204,0.037113,200.862975,1,True,3
2,LightGBMLarge,0.781362,0.919485,0.781362,0.781362,roc_auc,0.174113,0.153152,65.188701,0.174113,0.153152,65.188701,1,True,9
3,LightGBM,0.781095,0.919030,0.781095,0.781095,roc_auc,0.167712,0.196187,228.354290,0.167712,0.196187,228.354290,1,True,2
4,LightGBMXT,0.780646,0.918965,0.780646,0.780646,roc_auc,0.266048,0.873061,291.365826,0.266048,0.873061,291.365826,1,True,1
5,XGBoosttree,0.779046,0.918997,0.779046,0.779046,roc_auc,0.493690,0.267194,86.758784,0.493690,0.267194,86.758784,1,True,4
6,XGBoosttree_3,0.775896,0.919290,0.775896,0.775896,roc_auc,0.323460,0.312481,96.913277,0.323460,0.312481,96.913277,1,True,7
7,XGBoosttree_1,0.775534,0.918444,0.775534,0.775534,roc_auc,0.319357,0.338408,74.599018,0.319357,0.338408,74.599018,1,True,5
8,XGBoosttree_4,0.775345,0.918022,0.775345,0.775345,roc_auc,0.313715,0.272978,66.894486,0.313715,0.272978,66.894486,1,True,8
9,XGBoosttree_2,0.773050,0.918282,0.773050,0.773050,roc_auc,0.324655,0.348277,69.756819,0.324655,0.348277,69.756819,1,True,6
10,MultiModalPredictor,0.769677,0.918639,0.769677,0.769677,roc_auc,18.747947,18.729316,6114.856478,18.747947,18.729316,6114.856478,1,True,10

In [5]:
prediction = predictor.predict_proba(test_df, model=None)

Load pretrained checkpoint: /media/minhduck/SSD1/Documents/projects/AutoML-Platform/src/mlservice/app/test/relational_test/AutogluonModels/ag-20240226_134632/models/MultiModalPredictor/automm_model/model.ckpt

Predicting DataLoader 0: 100%|██████████| 1524/1524 [00:29<00:00, 52.07it/s]

In [ ]:
test_df['TARGET'] = prediction[1]

In [ ]:
test_df[['SK_ID_CURR', 'TARGET']].to_csv('sub.csv', index=False)